### ISSUE TITLE
id_token_hint

### ISSUE THREAD

**Issue by jschristie** [GluuFederation/docs-oxd-prod#1]
sakitA  commented 7 days ago • edited sakitA edited this issue 7 days ago 

On the documentation (Library->Java) logout example code is not correct. On the code shows that user can set  dummy  token for  id_token_hint  but it is not correct.  id_token_hint  must be obtained from OP server. Otherwise OP return  invalid_grant_type  error

**Comment by yuriyz** [comment]
fixed in 3.0.1 and 2.4.4 versions in https://github.com/GluuFederation/docs-oxd-prod repo
