### ISSUE TITLE
'python-flask' doc modification

### ISSUE THREAD

**Issue by mzico** [GluuFederation/docs-oxd-prod#29]
Little modifications required ( for now ) in python-flask doc: https://gluu.org/docs/oxd/3.1.2/libraries/framework/flask/

 - We need to install openjdk / oracle-java8 for oxd-server which is not available in Ubuntu 14.04.  ( https://gluu.org/docs/oxd/3.1.2/libraries/framework/flask/#software-requirements ) 
 -  `ox-conf.json` and other configuration files installed inside `/etc/oxd/oxd-server/`; not in `/opt/oxd-server/` ( https://gluu.org/docs/oxd/3.1.2/libraries/framework/flask/#configuring-oxd-server)

**Comment by centroxy** [comment]
Hi @mzico  the oxd-conf.json path is fixed now. Regarding openjdk or oracle-java8 for oxd-server, I think it is not required to mention in python flask document.

 Because openjdk or oracle-java8 is required for oxd server  installation

**Comment by mzico** [comment]
@centroxy : Make sense. Thanks.
