### ISSUE TITLE
Change 'oxd-id' with 'oxd_id'.

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/docs-oxd-prod#3]
In protocol and in code we use `oxd_id`, not `oxd-id`. Current 3.0.1 version has hyphen instead of underscore sign.

**Comment by jschristie** [comment]
@yuriyz will correct it and let you know.

**Comment by jschristie** [comment]
@yuriyz:

Whereever "oxd-id" was mentioned i have modified and renamed it to "oxd_id"
