### ISSUE TITLE
Fix broken/incorrect links in oxd-library documents in oxd 3.1.2 docs

### ISSUE THREAD

**Issue by mpavlov7** [GluuFederation/docs-oxd-prod#30]
**CSharp**
* Broken Links
    * Source from Github - Download the zip of the oxd CSharp library
        * https://codeload.github.com/GluuFederation/oxd-csharp/zip/3.1.2
    * oxd-csharp API docs for the auto-generated csharp docs
        * https://rawgit.com/GluuFederation/oxd-csharp/3.1.2/docs/html/index.html
    * See the code of a sample .Net app built using oxd-csharp
        * https://github.com/GluuFederation/oxd-csharp/tree/3.1.2/GluuDemoWebsite
    * The oxd_config.json file
        * https://github.com/GluuFederation/oxd-csharp/blob/3.1.2/GluuDemoWebsite/oxd_config.json

**Go**
* Broken Links
    * https://client.example.com/.well-known/openid-configuration
    * https://client.example.com/oxauth/.well-known/openid-configuration
* Wrong Links
    * uma_rpt_policies you can reference this document **(points to 3.1.1)**
        * https://gluu.org/docs/oxd/3.1.1/api/#uma-2-client-apis
    * Sample Project **(points to 3.1.1)**
        * https://github.com/GluuFederation/oxd-go/archive/3.1.1.zip

**Java**
* Wrong Links
    * Get User Info **(Listed as Site Registration instead of Register Site)**
    * uma_rpt_policies you can reference this document **(points to 3.1.1)**
        * https://gluu.org/docs/oxd/3.1.1/api/#uma-2-client-apis

**Node**
* Broken Links
    * Source from Github - Download
        * https://github.com/GluuFederation/oxd-node/archive/3.1.2.zip
    * Sample node app
        * https://github.com/GluuFederation/oxd-node/tree/3.1.2/oxd-node-demo

**Perl**
* Wrong Links
    * oxd-perl API docs for the auto-generated perl docs **(API link is already taken, rename something else)**
        * https://rawgit.com/GluuFederation/oxd-perl/3.1.2/docs/html/index.html

**PHP**
* Wrong Links
    * oxd-php API docs for the auto-generated perl docs **(API link is already taken, rename something else; Link doesn't exist)**
        * https://rawgit.com/GluuFederation/oxd-php-library/3.1.2/docs/html/index.html

**Python**
* Broken Links
    * Source from Github - Download 
        * https://codeload.github.com/GluuFederation/oxd-python/zip/3.1.2
    * Sample Flask App
        * https://github.com/GluuFederation/oxd-python/blob/3.1.2/examples/flask_app
    * sample.cfg file
        * https://github.com/GluuFederation/oxd-python/blob/3.1.2/sample.cfg
* Wrong Links
    * oxd-python API docs for the auto-generated perl docs **(API link is already taken, rename something else)**
        * https://rawgit.com/GluuFederation/oxd-python/3.1.2/docs/html/index.html

**Ruby**
* Wrong Links
    * oxd-ruby API docs for the auto-generated perl docs **(API link is already taken, rename something else)** 
        * http://www.rubydoc.info/gems/oxd-ruby/1.0.2

**Comment by willow9886** [comment]
@mpavlov7 im not sure this is correct... specifically, the links that "point to github instead of gluu site". Where are you looking at the docs? If you are looking at the doc on github, then the link should take you to another page. If you are looking at the doc on the gluu site, it should take you to the gluu site. Can you please confirm ?

**Comment by willow9886** [comment]
@mpavlov7 keep in mind the linking structure in the docs source code... we use relative links, e.g. `../../admin-guide/index.md`. When it gets pulled through to our official site, it keeps users on the official site. But when you're on github, it keeps you in the "source code".

**Comment by willow9886** [comment]
links are fixed.
