### ISSUE TITLE
Add document page for 'Redis configuration' in oxd 

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/docs-oxd-prod#69]
Add document page for 'Redis configuration' in oxd

**Comment by yuriyz** [comment]
@duttarnab please add "Redis" page under "Configuration" page. Also it would be nice to add H2 page.  

On H2 page we should consolidate H2 information:
- configuration example
- how to connect with H2 with H2 tools (move content from https://gluu.org/docs/oxd/4.0/faq/#how-can-i-view-data-inside-oxd-database-manually-without-oxd-server)
- steps how to connect with DBeaver

```
- Configuration
   - H2
   - Redis
```

**Comment by duttarnab** [comment]
Done by https://github.com/GluuFederation/docs-oxd-prod/pull/71
