### ISSUE TITLE
Add section with description of SSL configuration and `trust_all` option.

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/docs-oxd-prod#82]
Add doc section with details explanation of `trust_all` and SSL configuration.
```
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[?:1.8.0_222]
```

**Comment by duttarnab** [comment]
@yuriyz , I think description provided in https://www.gluu.org/docs/oxd/4.0/configuration/oxd-configuration/#server-configuration-fields-descriptions clearly explains `trust_all_certs` configuration. Do you think we need to provide any more details?

**Comment by yuriyz** [comment]
I guess yes since from time to time we get question from devs/customers what should they do if see error above.
There 2 points missed:
1. if customer found exception as shown above (in description) what should it do ? 
2. We should explain that safe way it to import certs into keystore and the other way is to ignore validation via `trust_all` property.

**Comment by duttarnab** [comment]
Done in 4.2.2
